LPD-20257 | Master
liferay-ac/liferay-portal pull request #1271
Opened 2024-03-14 22:08 UTC by interaminense

2024-03-14 22:08 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-03-14 22:21 UTC, interaminense commented
This PR depends on this one to be merged: https://github.com/liferay-frontend/liferay-portal/pull/4061

2024-03-14 23:11 UTC, marcellustavares requested changes
@interaminense

2024-03-14 23:11 UTC, marcellustavares commented on modules/apps/analytics/analytics-web/src/main/resources/META-INF/resources/dynamic_include/top_head.jsp
> +	function <portlet:namespace />checkLiferayDXPConsent() {
can we rename to `checkPerformanceCookieConsent` ?

2024-03-14 23:11 UTC, marcellustavares commented on modules/apps/analytics/analytics-web/src/main/resources/META-INF/resources/dynamic_include/top_head.jsp
> +	function <portlet:namespace />validateConsentCookie() {
can we rename to `isPerfomanceCookieConsented`?

2024-03-14 23:12 UTC, marcellustavares commented
@interaminense, I've made some minor function name request changes. Let me know if they make sense. Thanks

2024-03-18 13:49 UTC, marcosapmf commented
resent to https://github.com/liferay-ac/liferay-portal/pull/1275

2024-03-18 13:49 UTC, closed without merging