LPD-1195 Chart legend text color fix
liferay-ac/liferay-portal pull request #1526
Opened 2024-05-13 19:00 UTC by sillascavalcanti

2024-05-13 19:00 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-05-13 19:01 UTC, sillascavalcanti commented
ci:test:sf

2024-05-13 19:01 UTC, sillascavalcanti commented
ci:test:analytics-cloud-acceptance

2024-05-13 19:02 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>analytics-cloud-acceptance</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/11856/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11856/jenkins-report.html">here</a>.</b></p>

2024-05-13 19:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/3367/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3367/jenkins-report.html">here</a>.</b></p>

2024-05-13 19:05 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/77ae292bf9d7fe847a8b5b237ca52f064cc67a8c">77ae292bf9d7fe847a8b5b237ca52f064cc67a8c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/sillascavalcanti/liferay-portal/tree/LPD-1195">LPD-1195</a><br/>Branch GIT ID: <a href="https://github.com/sillascavalcanti/liferay-portal/commit/46dd3dbd656cd6a02bac3c6d77f5ef31fa7a4c11">46dd3dbd656cd6a02bac3c6d77f5ef31fa7a4c11</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/3367/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3367/jenkins-report.html">here</a>.</h5></details></html>

2024-05-13 19:10 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/3367/">test-portal-source-format#3367</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/3367/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-ac/liferay-portal/pull/1526">liferay-ac#1526</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2568249464">[master] ci:test:sf - sillascavalcanti &gt; liferay-ac - PR#1526 - 2024-05-13[12:01:42]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2568249464<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/13381/">publish-testray-report#13381</a><br/></div></div>

2024-05-13 20:34 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:analytics-cloud-acceptance - 1 out of 5 jobs passed in 1 hour 32 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/77ae292bf9d7fe847a8b5b237ca52f064cc67a8c">77ae292bf9d7fe847a8b5b237ca52f064cc67a8c</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/77ae292bf9d7fe847a8b5b237ca52f064cc67a8c">77ae292bf9d7fe847a8b5b237ca52f064cc67a8c</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2567814083">EE Development Acceptance (master) - 536 - 2024-05-10[08:38:08]</a></p><details><summary><strong>ci:test:analytics-cloud-acceptance - 1 out of 5 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/11856/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998400/"><strike>functional-tomcat90-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/951731/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998399/"><strike>functional-tomcat90-mysql57-jdk8/0/2</strike></a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/951732/">playwright-js-tomcat90-mysql57-jdk8/0/0</a></li></ul></li></ul></div><details><summary><strong>1 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11856/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998400//consoleText">functional-tomcat90-mysql57-jdk8/0/0</a><pre>     [exec] Volume com-liferay-osb-asah-private_faro not found.
     [exec] Removing volume com-liferay-osb-asah-private_mariadbdata
     [exec] Volume com-liferay-osb-asah-private_mariadbdata not found.
     [exec] Removing volume com-liferay-osb-asah-private_psqldata
     [exec] Volume com-liferay-osb-asah-private_psqldata not found.
     [exec] Removing volume com-liferay-osb-asah-private_storage
     [exec] Volume com-liferay-osb-asah-private_storage not found.
     [exec] Removing volume com-liferay-osb-asah-private_temp
     [exec] Volume com-liferay-osb-asah-private_temp not found.
     [exec] Error response from daemon: a disk usage operation is already running
[stopwatch] [test.execution.duration: 4:47.139 sec]
[stopwatch] [run.batch.test.action: 5:16.831 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:373: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1685: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1689: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:38: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:16347: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-analytics-cloud.xml:881: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-analytics-cloud.xml:850: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-common.xml:528: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-common.xml:647: exec returned: 1
      [get] Getting: \$\{dependencies.url\}/archive/test-1-32/test-portal-acceptance-pullrequest-downstream(master)/998400consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20240513132039374.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20240513132039374.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1672950475.properties</pre><ol><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998400//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_AssetsBlogs_ViewAllBlogsShownInAssetList_">LocalFile.AssetsBlogs#ViewAllBlogsShownInAssetList</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-27/test-portal-acceptance-pullrequest(master)/11856/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.AssetsBlogs_ViewAllBlogsShownInAssetList/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-27/test-portal-acceptance-pullrequest(master)/11856/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.AssetsBlogs_ViewAllBlogsShownInAssetList/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-27/test-portal-acceptance-pullrequest(master)/11856/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.AssetsBlogs_ViewAllBlogsShownInAssetList/console.txt.gz">Poshi Console</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-27/test-portal-acceptance-pullrequest(master)/11856/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998400//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_AssetsDocumentsAndMedia_VisitorBehaviorCardShowsExpectedAmountOfPreviewsInDM_">LocalFile.AssetsDocumentsAndMedia#VisitorBehaviorCardShowsExpectedAmountOfPreviewsInDM</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-27/test-portal-acceptance-pullrequest(master)/11856/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.AssetsDocumentsAndMedia_VisitorBehaviorCardShowsExpectedAmountOfPreviewsInDM/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-27/test-portal-acceptance-pullrequest(master)/11856/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.AssetsDocumentsAndMedia_VisitorBehaviorCardShowsExpectedAmountOfPreviewsInDM/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-27/test-portal-acceptance-pullrequest(master)/11856/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.AssetsDocumentsAndMedia_VisitorBehaviorCardShowsExpectedAmountOfPreviewsInDM/console.txt.gz">Poshi Console</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-27/test-portal-acceptance-pullrequest(master)/11856/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/998400//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Properties_PropertiesListInSettingsShowsListOfAllPropertiesInTheWorkspace_">LocalFile.Properties#PropertiesListInSettingsShowsListOfAllPropertiesInTheWorkspace</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-27/test-portal-acceptance-pullrequest(mast [...]

2024-05-13 20:38 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/11856/">test-portal-acceptance-pullrequest(master)#11856</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11856/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>analytics-cloud-acceptance<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-ac/liferay-portal/pull/1526">liferay-ac#1526</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1553080605">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2568259379">[master] ci:test:analytics-cloud-acceptance - sillascavalcanti &gt; liferay-ac - PR#1526 - 2024-05-13[12:02:00]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2568259379<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/25887/">publish-testray-report#25887</a><br/></div></div>

2024-05-14 16:42 UTC, marcosapmf commented
acceptance errors are probably fixed in https://github.com/liferay-ac/liferay-portal/pull/1528

2024-05-16 17:26 UTC, interaminense requested changes
@sillascavalcanti can you take a look at my comments?

2024-05-16 19:49 UTC, sillascavalcanti commented
ci:test:sf

2024-05-16 19:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/5618/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5618/jenkins-report.html">here</a>.</b></p>

2024-05-16 19:54 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6cb31200eda5752c4d276424f64abf0dbb2fe7a1">6cb31200eda5752c4d276424f64abf0dbb2fe7a1</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/sillascavalcanti/liferay-portal/tree/LPD-1195">LPD-1195</a><br/>Branch GIT ID: <a href="https://github.com/sillascavalcanti/liferay-portal/commit/67ba5131138e40defea776c818787f4329d923ec">67ba5131138e40defea776c818787f4329d923ec</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-source-format/5618/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5618/jenkins-report.html">here</a>.</h5></details></html>

2024-05-16 19:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-source-format/5618/">test-portal-source-format#5618</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/5618/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-ac/liferay-portal/pull/1526">liferay-ac#1526</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2569524852">[master] ci:test:sf - sillascavalcanti &gt; liferay-ac - PR#1526 - 2024-05-16[12:49:58]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2569524852<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/21922/">publish-testray-report#21922</a><br/></div></div>

2024-05-16 20:34 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>analytics-cloud-acceptance</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/10629/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10629/jenkins-report.html">here</a>.</b></p>

2024-05-16 21:30 UTC, interaminense requested changes

2024-05-16 21:30 UTC, interaminense commented on modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/css/_chart_legend.scss
> +	color:$mainLighten28;
Could you add space between color and variable?

2024-05-16 21:30 UTC, interaminense commented on modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/components/metric-card/MetricChart.tsx
> +										<span className='legend-text-color'>
Is it needed since you already added className at 404 line?

2024-05-16 21:30 UTC, interaminense commented on modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/components/metric-card/MetricChart.tsx
> +											<b className='ml-1'>{value}</b>
Could you break line between label and <b /> tag?

2024-05-17 01:29 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:analytics-cloud-acceptance - 1 out of 5 jobs passed in 4 hours 55 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6cb31200eda5752c4d276424f64abf0dbb2fe7a1">6cb31200eda5752c4d276424f64abf0dbb2fe7a1</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6cb31200eda5752c4d276424f64abf0dbb2fe7a1">6cb31200eda5752c4d276424f64abf0dbb2fe7a1</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2569688134">EE Development Acceptance (master) - 542 - 2024-05-16[12:39:18]</a></p><details><summary><strong>ci:test:analytics-cloud-acceptance - 1 out of 5 jobs PASSED</strong></summary><div><h4>4 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/10629/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/636617/"><strike>functional-tomcat90-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/898745/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/636616/">functional-tomcat90-mysql57-jdk8/0/2</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/898746/"><strike>playwright-js-tomcat90-mysql57-jdk8/0/0</strike></a></li></ul></li></ul></div><details><summary><strong>1 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10629/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/898745//consoleText">functional-tomcat90-mysql57-jdk8/0/1</a><pre>     [exec] Removing faro                 ... done
     [exec] Network test-1-29-5 is external, skipping
     [exec] Removing volume com-liferay-osb-asah-private_backup
     [exec] Removing volume com-liferay-osb-asah-private_export
     [exec] Removing volume com-liferay-osb-asah-private_faro
     [exec] Removing volume com-liferay-osb-asah-private_mariadbdata
     [exec] Removing volume com-liferay-osb-asah-private_psqldata
     [exec] Removing volume com-liferay-osb-asah-private_storage
     [exec] Removing volume com-liferay-osb-asah-private_temp
     [exec] TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
     [exec] Images          87        5         80.39GB   70.53GB (87%)
     [exec] Containers      8         8         15.46GB   0B (0%)
     [exec] Local Volumes   2         2         663.7MB   0B (0%)
     [exec] Build Cache     25        0         0B        0B
[stopwatch] [test.execution.duration: 14:41.567 sec]
[stopwatch] [run.batch.test.action: 15:12.432 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:373: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1685: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1689: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:38: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:16357: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-analytics-cloud.xml:883: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-analytics-cloud.xml:739: Failed to start Analytics Cloud with error code 143.
      [get] Getting: \$\{dependencies.url\}/archive/test-1-29/test-portal-acceptance-pullrequest-downstream(master)/898745consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20240516181655586.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20240516181655586.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null858942884.properties</pre><ol><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/898745//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_AssetsCustomAsset_CanCreateMultipleCustomAssetReport_">LocalFile.AssetsCustomAsset#CanCreateMultipleCustomAssetReport</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-38/test-portal-acceptance-pullrequest(master)/10629/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.AssetsCustomAsset_CanCreateMultipleCustomAssetReport/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-38/test-portal-acceptance-pullrequest(master)/10629/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.AssetsCustomAsset_CanCreateMultipleCustomAssetReport/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-38/test-portal-acceptance-pullrequest(master)/10629/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.AssetsCustomAsset_CanCreateMultipleCustomAssetReport/console.txt.gz">Poshi Console</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-38/test-portal-acceptance-pullrequest(master)/10629/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/636617//consoleText">functional-tomcat90-mysql57-jdk8/0/0</a><ol><li><div><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/636617//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_AssetsDocumentsAndMedia_VisitorBehaviorCardShowsExpectedAmountOfPreviewsInDM_">LocalFile.AssetsDocumentsAndMedia#VisitorBehaviorCardShowsExpectedAmountOfPreviewsInDM</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-38/test-portal-acceptance-pullrequest(master)/10629/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.AssetsDocumentsAndMedia_VisitorBehaviorCardShowsExpectedAmountOfPreviewsInDM/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-38/test-portal-acceptance-pullrequest(master)/10629/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.AssetsDocumentsAndMedia_VisitorBehaviorCardShowsExpectedAmountOfPreviewsInDM/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-38/test-portal-acceptance-pullrequest(master)/10629/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.AssetsDocumentsAndMedia_VisitorBehaviorCardShowsExpectedAmountOfPreviewsInDM/console.txt.gz">Poshi Console</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-38/test-portal-acceptance-pullrequest(master)/10629/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/636617//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Properties_PropertiesListInSettingsShowsListO [...]

2024-05-17 01:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/10629/">test-portal-acceptance-pullrequest(master)#10629</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10629/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>analytics-cloud-acceptance<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-ac/liferay-portal/pull/1526">liferay-ac#1526</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1553080605">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2569709187">[master] ci:test:analytics-cloud-acceptance - sillascavalcanti &gt; liferay-ac - PR#1526 - 2024-05-16[13:33:43]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2569709187<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/21926/">publish-testray-report#21926</a><br/></div></div>

2024-05-17 10:55 UTC, ViniLopes20 commented
ci:test:analytics-cloud-acceptance

2024-05-17 11:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>analytics-cloud-acceptance</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/5932/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5932/jenkins-report.html">here</a>.</b></p>

2024-05-17 12:57 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:analytics-cloud-acceptance - 3 out of 5 jobs passed in 1 hour 50 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6cb31200eda5752c4d276424f64abf0dbb2fe7a1">6cb31200eda5752c4d276424f64abf0dbb2fe7a1</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6cb31200eda5752c4d276424f64abf0dbb2fe7a1">6cb31200eda5752c4d276424f64abf0dbb2fe7a1</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2569688134">EE Development Acceptance (master) - 542 - 2024-05-16[12:39:18]</a></p><details><summary><strong>ci:test:analytics-cloud-acceptance - 3 out of 5 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/5932/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/637552/"><strike>functional-tomcat90-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/637551/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/637550/">functional-tomcat90-mysql57-jdk8/0/2</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/637553/">playwright-js-tomcat90-mysql57-jdk8/0/0</a></li></ul></li></ul></div><details><summary><strong>3 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5932/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/637552//consoleText">functional-tomcat90-mysql57-jdk8/0/0</a><pre>     [exec] Removing faro                 ... done
     [exec] Network test-1-40-35 is external, skipping
     [exec] Removing volume com-liferay-osb-asah-private_backup
     [exec] Removing volume com-liferay-osb-asah-private_export
     [exec] Removing volume com-liferay-osb-asah-private_faro
     [exec] Removing volume com-liferay-osb-asah-private_mariadbdata
     [exec] Removing volume com-liferay-osb-asah-private_psqldata
     [exec] Removing volume com-liferay-osb-asah-private_storage
     [exec] Removing volume com-liferay-osb-asah-private_temp
     [exec] TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
     [exec] Images          88        5         89.92GB   80.26GB (89%)
     [exec] Containers      6         6         22.98GB   0B (0%)
     [exec] Local Volumes   26        1         4.738GB   4.38GB (92%)
     [exec] Build Cache     25        0         0B        0B
[stopwatch] [test.execution.duration: 14:40.774 sec]
[stopwatch] [run.batch.test.action: 15:11.367 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:373: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1685: /opt/dev/projects/github/liferay-portal/build-test-batch.xml:1689: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:38: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-tomcat.xml:50: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test.xml:16357: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-analytics-cloud.xml:883: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-analytics-cloud.xml:739: Failed to start Analytics Cloud with error code 143.
      [get] Getting: http://test-1-40/job/test-portal-acceptance-pullrequest-downstream(master)/637552//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20240517055548331.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20240517055548331.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null184785707.properties</pre><ol><li><div><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/637552//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_AssetsBlogs_ViewAllBlogsShownInAssetList_">LocalFile.AssetsBlogs#ViewAllBlogsShownInAssetList</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-33/test-portal-acceptance-pullrequest(master)/5932/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.AssetsBlogs_ViewAllBlogsShownInAssetList/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-33/test-portal-acceptance-pullrequest(master)/5932/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.AssetsBlogs_ViewAllBlogsShownInAssetList/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-33/test-portal-acceptance-pullrequest(master)/5932/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.AssetsBlogs_ViewAllBlogsShownInAssetList/console.txt.gz">Poshi Console</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-33/test-portal-acceptance-pullrequest(master)/5932/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/637552//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_AssetsDocumentsAndMedia_VisitorBehaviorCardShowsExpectedAmountOfPreviewsInDM_">LocalFile.AssetsDocumentsAndMedia#VisitorBehaviorCardShowsExpectedAmountOfPreviewsInDM</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-33/test-portal-acceptance-pullrequest(master)/5932/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.AssetsDocumentsAndMedia_VisitorBehaviorCardShowsExpectedAmountOfPreviewsInDM/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-33/test-portal-acceptance-pullrequest(master)/5932/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.AssetsDocumentsAndMedia_VisitorBehaviorCardShowsExpectedAmountOfPreviewsInDM/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-33/test-portal-acceptance-pullrequest(master)/5932/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.AssetsDocumentsAndMedia_VisitorBehaviorCardShowsExpectedAmountOfPreviewsInDM/console.txt.gz">Poshi Console</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-33/test-portal-acceptance-pullrequest(master)/5932/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/637552//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Properties_PropertiesListInSettingsShowsListOfAllPropertiesInTheWorkspace_">LocalFile.Properties#PropertiesListInSettingsShowsListOfAllPropertiesInTheWorkspace</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-33/test-portal-acceptance-pullrequest(master)/5932/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.Propertie [...]

2024-05-17 13:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/5932/">test-portal-acceptance-pullrequest(master)#5932</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5932/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>analytics-cloud-acceptance<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-ac/liferay-portal/pull/1526">liferay-ac#1526</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1553080605">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2570072639">[master] ci:test:analytics-cloud-acceptance - sillascavalcanti &gt; liferay-ac - PR#1526 - 2024-05-17[04:07:49]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2570072639<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/12951/">publish-testray-report#12951</a><br/></div></div>

2024-05-17 16:20 UTC, sillascavalcanti commented
ci:test:sf

2024-05-17 16:21 UTC, sillascavalcanti commented
ci:test:relevant

2024-05-17 16:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-source-format/7704/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7704/jenkins-report.html">here</a>.</b></p>

2024-05-17 16:40 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f7edb89c55414ddc679deb307d7101c9b0603e65">f7edb89c55414ddc679deb307d7101c9b0603e65</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/sillascavalcanti/liferay-portal/tree/LPD-1195">LPD-1195</a><br/>Branch GIT ID: <a href="https://github.com/sillascavalcanti/liferay-portal/commit/04280628ae5a4ba38c8a591700d7cc44807638dd">04280628ae5a4ba38c8a591700d7cc44807638dd</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7704/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7704/jenkins-report.html">here</a>.</h5></details></html>

2024-05-17 16:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-source-format/7704/">test-portal-source-format#7704</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/7704/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-ac/liferay-portal/pull/1526">liferay-ac#1526</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2570097344">[master] ci:test:sf - sillascavalcanti &gt; liferay-ac - PR#1526 - 2024-05-17[09:35:19]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2570097344<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/4070/">publish-testray-report#4070</a><br/></div></div>

2024-05-17 17:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/10640/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10640/jenkins-report.html">here</a>.</b></p>

2024-05-17 18:34 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 29 out of 30 jobs passed</h3><h3>:x: ci:test:relevant - 36 out of 38 jobs passed in 1 hour 29 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f7edb89c55414ddc679deb307d7101c9b0603e65">f7edb89c55414ddc679deb307d7101c9b0603e65</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6cb31200eda5752c4d276424f64abf0dbb2fe7a1">6cb31200eda5752c4d276424f64abf0dbb2fe7a1</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2569688134">EE Development Acceptance (master) - 542 - 2024-05-16[12:39:18]</a></p><details><summary><strong>ci:test:stable - 29 out of 30 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>build-iw-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1107804/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1108912/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1005067/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/596886/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/637766/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/596887/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/885372/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1107808/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/4</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1108913/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/5</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1013682/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/829868/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1005068/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/885369/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/637764/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/596885/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/637765/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1107807/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1005070/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1005069/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1108911/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1107805/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/829869/">modules-compile-jdk8/0/11</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/885371/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/829871/">modules-integration-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/885370/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1005066/">playwright-compile-jdk8/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1108922/">playwright-js-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/829870/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1005065/"><strike>unit-jdk8_stable/0/0</strike></a></li></ul></li><li>workspaces-compile-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1005064/">workspaces-compile-jdk8/0/0</a></li></ul></li></ul></div><details><summary><strong>29 Successful Jobs:</strong></summary><ul/></details></details><details><summary><strong>ci:test:relevant - 36 out of 38 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/10640/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1107804/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1108912/">central-requirements-jdk8/0/0</a></li></ul></li><li>empty-osgi-core-dir-mysql57-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1005063/">empty-osgi-core-dir-mysql57-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1005067/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/596886/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/637766/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/596887/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/885372/">functional-upgrade-tomcat90-my [...]

2024-05-17 18:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/10640/">test-portal-acceptance-pullrequest(master)#10640</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10640/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-ac/liferay-portal/pull/1526">liferay-ac#1526</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2570136317">[master] ci:test:relevant - sillascavalcanti &gt; liferay-ac - PR#1526 - 2024-05-17[10:04:28]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2570136317<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/21942/">publish-testray-report#21942</a><br/></div></div>

2024-05-17 18:51 UTC, sillascavalcanti commented
ci:test:stable

2024-05-17 18:52 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>stable</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/10134/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10134/jenkins-report.html">here</a>.</b></p>

2024-05-17 20:30 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 30 out of 32 jobs passed in 1 hour 39 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f7edb89c55414ddc679deb307d7101c9b0603e65">f7edb89c55414ddc679deb307d7101c9b0603e65</a></p><details><summary><strong>ci:test:stable - 30 out of 32 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/10134/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>build-iw-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/637878/">build-iw-jdk8/0/0</a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/920677/">central-requirements-jdk8/0/0</a></li></ul></li><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/829962/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1013713/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/829965/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/885467/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/596974/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/3</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/427034/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/4</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/945538/"><strike>functional-upgrade-tomcat90-mysql57-jdk8_stable/0/5</strike></a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1107942/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1107913/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1109008/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/829963/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/596972/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/945537/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/596973/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/637881/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1109010/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1109009/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/829964/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/637879/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/885465/">modules-compile-jdk8/0/11</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/899633/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/957313/">modules-integration-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/885466/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>playwright-compile-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1109007/">playwright-compile-jdk8/0/0</a></li></ul></li><li>playwright-js-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1107915/">playwright-js-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/637880/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1107914/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/829961/">unit-jdk8_stable/0/0</a></li></ul></li><li>workspaces-compile-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/829960/">workspaces-compile-jdk8/0/0</a></li></ul></li></ul></div><details><summary><strong>30 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10134/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/945538//consoleText">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/5</a><ol><li><div><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/945538//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PortalSmokeUpgrade_ViewPortalSmokeArchive7413_">LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive7413</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-39/test-portal-acceptance-pullrequest(master)/10134/functional-upgrade-tomcat90-mysql57-jdk8_stable/0/5/LocalFile.PortalSmokeUpgrade_ViewPortalSmokeArchive7413/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-39/test-portal-acceptance-pullrequest(master)/10134/functional-upgrade-tomcat90-mysql57-jdk8_stable/0/5/LocalFile.PortalSmokeUpgrade_ViewPortalSmokeArchive7413/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-39/test-portal-acceptance-pullrequest(master)/10134/functional-upgrade-tomcat90-mysql57-jdk8_stable/0/5/LocalFile.PortalSmokeUpgrade_ViewPortalSmokeArchive7413/console.txt.gz">Poshi Console</a> - <a href="https://testray.liferay.com/reports/production/logs/2024-05/test-1-39/test-portal-acceptance-pullrequest(master)/10134/functional-upgrade-tomcat90-mysql57-jdk8_stable/0/5/jenkins-console.txt.gz">Console Output</a> - <a href="https://testray.liferay.com/home/-/testray/case_results/2569700261/history">Failed 0 of last 13</a></div></li></ol></div></li></ol><h4>For  [...]

2024-05-17 20:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/10134/">test-portal-acceptance-pullrequest(master)#10134</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10134/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>stable<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-ac/liferay-portal/pull/1526">liferay-ac#1526</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2570242610">[master] ci:test:stable - sillascavalcanti &gt; liferay-ac - PR#1526 - 2024-05-17[11:52:08]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2570242610<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/21699/">publish-testray-report#21699</a><br/></div></div>

2024-05-18 23:14 UTC, interaminense commented
ci:test:stable

2024-05-20 18:55 UTC, sillascavalcanti commented
Manually forwarded to https://github.com/brianchandotcom/liferay-portal/pull/150492

2024-05-21 12:39 UTC, closed without merging