AC New Test - LPD-29404 | master
liferay-ac/liferay-portal pull request #1659
Opened 2024-06-26 15:33 UTC by ViniLopes20

https://liferay.atlassian.net/browse/LPD-29404

2024-06-26 15:33 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2024-07-01 13:55 UTC, marcosapmf commented
ci:report:28576492

2024-07-01 13:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running <code>generate testray csv</code> for testrayBuildID: <b>28576492</b>.</p><p>Job Link: <a href="https://test-1-33.liferay.com/job/generate-testray-csv/207/">generate-testray-csv</a></p>

2024-07-01 13:57 UTC, liferay-continuous-integration commented
<h1>Build completed.</h1><p>Testray CSV has been generated successfully for testrayBuildID: <b>28576492</b>.</p><p>Job Link: <a href="https://test-1-33.liferay.com/job/generate-testray-csv/207/">generate-testray-csv</a></p><p>Testray CSV Link: <a href="https://test-1-33.liferay.com/userContent/jobs/generate-testray-csv/builds/207/testray-results-28576492.csv">testray-results-28576492.csv</a></p>

2024-07-02 12:38 UTC, marcosapmf commented
ci:report:29207888

2024-07-02 12:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running <code>generate testray csv</code> for testrayBuildID: <b>29207888</b>.</p><p>Job Link: <a href="https://test-1-26.liferay.com/job/generate-testray-csv/195/">generate-testray-csv</a></p>

2024-07-02 12:41 UTC, liferay-continuous-integration commented
<h1>Build completed.</h1><p>Testray CSV has been generated successfully for testrayBuildID: <b>29207888</b>.</p><p>Job Link: <a href="https://test-1-26.liferay.com/job/generate-testray-csv/195/">generate-testray-csv</a></p><p>Testray CSV Link: <a href="https://test-1-26.liferay.com/userContent/jobs/generate-testray-csv/builds/195/testray-results-29207888.csv">testray-results-29207888.csv</a></p>

2024-07-02 14:19 UTC, interaminense commented
ci:test:analytics-cloud-acceptance

2024-07-02 14:20 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>analytics-cloud-acceptance</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/17296/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/17296/jenkins-report.html">here</a>.</b></p>

2024-07-02 14:21 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:analytics-cloud-acceptance - 0 out of 1 jobs passed in 1 minute</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a510315656c9b23e6a85b84b3d5b8128873a6b11">a510315656c9b23e6a85b84b3d5b8128873a6b11</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4c0331977d3d50b040e743e7b5e392905c7c607a">4c0331977d3d50b040e743e7b5e392905c7c607a</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/#/project/34754/routines/174485/build/26603560">EE Development Acceptance (master) - 625 - 2024-06-26[04:50:55]</a></p><details><summary><strong>ci:test:analytics-cloud-acceptance - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/17296/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/17296/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/17296/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><div><p>Please fix <strong>rebase errors</strong> on <strong><a href="https://github.com/liferay-ac/liferay-portal/pull/1659">ViniLopes20/LPD-29404</a></strong><pre>Unable to rebase master-temp-1719930047205 to master
Rebasing (1/11)
Rebasing (2/11)
Rebasing (3/11)
Rebasing (4/11)
Rebasing (5/11)
Rebasing (6/11)
Rebasing (7/11)
Rebasing (8/11)
error: could not apply 01752665008eb... LPD-29404 Add the new automation test to cover the case of the segment not appearing in the audience card after deletion
hint: Resolve all conflicts manually, mark them as resolved with
hint: "git add/rm &lt;conflicted_files&gt;", then run "git rebase --continue".
hint: You can instead skip this commit: run "git rebase --skip".
hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply 01752665008eb... LPD-29404 Add the new automation test to cover the case of the segment not appearing in the audience card after deletion</pre></p></div></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2024-07-02 14:23 UTC, interaminense requested changes

2024-07-02 14:23 UTC, interaminense commented on modules/test/playwright/tests/osb-faro-web/utils/selectors.ts
> +export enum cardSelector {
Hey @ViniLopes20, enum should start with the first letter uppercase.

2024-07-02 17:13 UTC, marcosapmf commented
@ViniLopes20 
resent to https://github.com/liferay-ac/liferay-portal/pull/1663

2024-07-02 17:13 UTC, closed without merging