LPD-43304 | master
liferay-ac/liferay-portal pull request #1965
Opened 2024-12-04 18:53 UTC by CaioERP

https://liferay.atlassian.net/browse/LPD-43304

2024-12-04 19:18 UTC, fmarcio commented
ci:test:sf

2024-12-04 19:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-source-format/5816/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5816/jenkins-report.html">here</a>.</b></p>

2024-12-04 19:24 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/103d781e63db4b84fb8e0e26040bceff618a7d5f">103d781e63db4b84fb8e0e26040bceff618a7d5f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/CaioERP/liferay-portal/tree/LPD-43304">LPD-43304</a><br/>Branch GIT ID: <a href="https://github.com/CaioERP/liferay-portal/commit/96b94ccd6249e04b444a158ff604bae7ee14c2f9">96b94ccd6249e04b444a158ff604bae7ee14c2f9</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-source-format/5816/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5816/jenkins-report.html">here</a>.</h5></details></html>

2024-12-04 19:38 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-source-format/5816/">test-portal-source-format#5816</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/5816/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-ac/liferay-portal/pull/1965">liferay-ac#1965</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/83758600">[master] ci:test:sf - CaioERP &gt; liferay-ac - PR#1965 - 2024-12-04[11:18:22]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>83758600<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/6433/">publish-testray-report#6433</a><br/></div></div>

2024-12-05 15:19 UTC, fmarcio commented on modules/dxp/apps/osb/osb-faro/osb-faro-web/src/main/js/shared/components/base-page/Header.tsx
> +						{label === 'Static Segment' && (
hey @CaioERP please check if its ok to use the same logic we discussed today

`deprecated && (...)`

2024-12-05 16:18 UTC, interaminense requested changes

2024-12-10 19:21 UTC, fmarcio commented
resent to https://github.com/liferay-ac/liferay-portal/pull/1979

2024-12-10 19:21 UTC, closed without merging