LRAC-12639 - [F] Create unit tests for Default Group Pages
liferay-ac/liferay-portal pull request #230
Opened 2022-12-22 17:29 UTC by ilzamcmed

2022-12-22 17:29 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-12-28 15:02 UTC, interaminense requested changes
Thank you for your hard work on these unit tests @ilzamcmed! Just a fix below.

2023-01-03 15:31 UTC, fmarcio approved these changes
Once you're done with @interaminense change request, LGTM!

2023-01-04 20:05 UTC, fmarcio commented
resent to https://github.com/liferay-ac/liferay-portal/pull/246

2023-01-04 20:05 UTC, closed without merging