LRAC-11380
liferay-ac/liferay-portal pull request #29
Opened 2022-06-17 21:47 UTC by ViniLopes20

2022-06-17 21:47 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-06-17 21:49 UTC, ViniLopes20 commented
ci:test:sf

2022-06-17 21:51 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/1812/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1812/jenkins-report.html">here</a>.</b></p>

2022-06-17 21:53 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fd14dbe69f730c0a07464e8996c1010942dcb484">fd14dbe69f730c0a07464e8996c1010942dcb484</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ViniLopes20/liferay-portal/tree/LRAC-11380">LRAC-11380</a><br/>Branch GIT ID: <a href="https://github.com/ViniLopes20/liferay-portal/commit/eb9f7fcdef22b10c9a054a39f13f29890562763f">eb9f7fcdef22b10c9a054a39f13f29890562763f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-source-format/1812/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1812/jenkins-report.html">here</a>.</h5></details></html>

2022-06-17 21:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/1812/">test-portal-source-format#1812</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1812/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-ac/liferay-portal/pull/29">liferay-ac#29</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1882302337">[master] ci:test:sf - ViniLopes20 &gt; liferay-ac - PR#29 - 2022-06-17[14:50:06]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/6909/">publish-testray-report#6909</a><br/></div></div>

2022-06-24 18:11 UTC, christianstokes requested changes
This test looks really nice Vini. I think you can look into using Poshi's DateUtil.getTimeInMilliseconds for the date variables, but overall the test looks good to me.

2022-06-28 19:36 UTC, ViniLopes20 commented on portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACUtils.macro
> +
Hey @christianstokes, that was a good suggestion. This macro works, but only for the current day, we cannot use it with a specific date. So I think the best solution would be to use this site to do that.

2022-06-28 19:51 UTC, ViniLopes20 commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/IdentityEvents.testcase
> +
Hey @christianstokes, I didn't understand the logic you wanted to show for this situation. Do you think that if we decrease the day in milliseconds with 604,800,000 we should get the result of 7 days ago?

2022-06-29 16:41 UTC, christianstokes commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/IdentityEvents.testcase
> +
Clarified in a conversation with Vini over slack. He will try using Poshi's dateUtil to get the current date in millis, then subtracting 86,400,000 per day to get to the value needed for the test.

2022-08-04 17:52 UTC, christianstokes commented
Hey @ViniLopes20 any updates on this? Since https://issues.liferay.com/browse/POSHI-374 is done?

2022-08-04 18:03 UTC, ViniLopes20 commented
> Hey @ViniLopes20 any updates on this? Since https://issues.liferay.com/browse/POSHI-374 is done?

Hey @christianstokes, I talked to Calum and he said he finished the implementation, but the change won't be available until the next Poshi release. I'm following the channel to see when it's released.

2022-08-15 22:52 UTC, ViniLopes20 commented
ci:test:sf

2022-08-15 22:53 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/3064/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/3064/jenkins-report.html">here</a>.</b></p>

2022-08-15 22:55 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/62f3e2f73e7ac48f81c19bc25e9396abc1004044">62f3e2f73e7ac48f81c19bc25e9396abc1004044</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ViniLopes20/liferay-portal/tree/LRAC-11380">LRAC-11380</a><br/>Branch GIT ID: <a href="https://github.com/ViniLopes20/liferay-portal/commit/a1bf62a679983abb2d2da541e8fff6266f616679">a1bf62a679983abb2d2da541e8fff6266f616679</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/3064/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/3064/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: ./portal-web/test/functional/com/liferay/portalweb/macros/analyticscloud/ACUtils.macro expected:&lt;...= "5000");
     [java]     \}
     [java]   \}
     [java] 
     [java] \}[]&gt; but was:&lt;...= "5000");
     [java]     \}
     [java]   \}
     [java] 
     [java] \}[
     [java] ]&gt;
     [java] 2: ./portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/IdentityEvents.testcase expected:&lt;...millisecondsValue = [\$\{currentMillisecondsValue\} - 86400000;
     [java]     \}
     [java] 
     [java]     task ("Change the local storage with the new value") \{
     [java]       ACUtils.setLocalStorageValue(
     [java]         keyName = "ac_client_identity_last_updated_date",
     [java]         keyValue = "\$\{millisecondsValue\}");
     [java]     \}
     [java] 
     [java]     task ("Get number from local storage") \{
     [java]       var localStorageItem1 = ACUtils.getLocalStorageItem(keyName = "ac_client_identity_last_updated_date");
     [java]     \}
     [java] 
     [java]     task ("Check if the present value in the local storage is equal to the converted") \{
     [java]       TestUtils.assertEquals(
     [java]         actual = "\$\{localStorageItem1\}",
     [java]         expected = "\$\{millisecondsValue\}");
     [java]     \}
     [java] 
     [java]     task ("Hard refresh the page") \{
     [java]       TestUtils.hardRefresh();
     [java]     \}
     [java] 
     [java]     task ("Get number from local storage") \{
     [java]       var actualMillisecondsValue = ACUtils.getLocalStorageItem(keyName = "ac_client_identity_last_updated_date");
     [java]     \}
     [java] 
     [java]     task ("Check if the present value in the local storage is equal to the converted") \{
     [java]       TestUtils.assertEquals(
     [java]         actual = "\$\{actualMillisecondsValue\}",
     [java]         expected = "\$\{millisecondsValue\}");
     [java]     \}
     [java]   \}
     [java] 
     [java]   @description = "Feature ID: LRAC-10998 | Automation ID: LRAC-11381 | Test Summary: Check that the Identify event is resent if the user stays logged in for more than 7 days and check if the same individual has not been counted twice when the event is resent"
     [java]   @priority = "5"
     [java]   test CheckIdentityEventResentIfUserStaysLoggedForMoreThan7days \{
     [java]     property proxy.server.enabled = "true";
     [java] 
     [java]     task ("Add a new user") \{
     [java]       JSONUser.addUser(
     [java]         userEmailAddress = "user2@liferay.com",</pre></details></html>

2022-08-15 22:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/3064/">test-portal-source-format#3064</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/3064/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-ac/liferay-portal/pull/29">liferay-ac#29</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1946620202">[master] ci:test:sf - ViniLopes20 &gt; liferay-ac - PR#29 - 2022-08-15[15:52:23]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/11273/">publish-testray-report#11273</a><br/></div></div>

2022-08-15 23:00 UTC, ViniLopes20 commented
ci:test:sf

2022-08-15 23:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/1009/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1009/jenkins-report.html">here</a>.</b></p>

2022-08-15 23:03 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/62f3e2f73e7ac48f81c19bc25e9396abc1004044">62f3e2f73e7ac48f81c19bc25e9396abc1004044</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ViniLopes20/liferay-portal/tree/LRAC-11380">LRAC-11380</a><br/>Branch GIT ID: <a href="https://github.com/ViniLopes20/liferay-portal/commit/a3b0e4baa211e35fa6c78f8a5a6d8ba2b10ef3ed">a3b0e4baa211e35fa6c78f8a5a6d8ba2b10ef3ed</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/1009/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1009/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/IdentityEvents.testcase expected:&lt;...millisecondsValue = [\$\{currentMillisecondsValue\} - 86400000;
     [java]     \}
     [java] 
     [java]     task ("Change the local storage with the new value") \{
     [java]       ACUtils.setLocalStorageValue(
     [java]         keyName = "ac_client_identity_last_updated_date",
     [java]         keyValue = "\$\{millisecondsValue\}");
     [java]     \}
     [java] 
     [java]     task ("Get number from local storage") \{
     [java]       var localStorageItem1 = ACUtils.getLocalStorageItem(keyName = "ac_client_identity_last_updated_date");
     [java]     \}
     [java] 
     [java]     task ("Check if the present value in the local storage is equal to the converted") \{
     [java]       TestUtils.assertEquals(
     [java]         actual = "\$\{localStorageItem1\}",
     [java]         expected = "\$\{millisecondsValue\}");
     [java]     \}
     [java] 
     [java]     task ("Hard refresh the page") \{
     [java]       TestUtils.hardRefresh();
     [java]     \}
     [java] 
     [java]     task ("Get number from local storage") \{
     [java]       var actualMillisecondsValue = ACUtils.getLocalStorageItem(keyName = "ac_client_identity_last_updated_date");
     [java]     \}
     [java] 
     [java]     task ("Check if the present value in the local storage is equal to the converted") \{
     [java]       TestUtils.assertEquals(
     [java]         actual = "\$\{actualMillisecondsValue\}",
     [java]         expected = "\$\{millisecondsValue\}");
     [java]     \}
     [java]   \}
     [java] 
     [java]   @description = "Feature ID: LRAC-10998 | Automation ID: LRAC-11381 | Test Summary: Check that the Identify event is resent if the user stays logged in for more than 7 days and check if the same individual has not been counted twice when the event is resent"
     [java]   @priority = "5"
     [java]   test CheckIdentityEventResentIfUserStaysLoggedForMoreThan7days \{
     [java]     property proxy.server.enabled = "true";
     [java] 
     [java]     task ("Add a new user") \{
     [java]       JSONUser.addUser(
     [java]         userEmailAddress = "user2@liferay.com",
     [java]         userFirstName = "user2",
     [java]         userLastName = "user2",
     [java]         userScreenName = "user2");
     [java] 
     [java]       JSONUser.setFirstPassword(
     [java]         agreeToTermsAndAnswerReminderQuery = "true",
     [java]         requireReset = "false",</pre></details></html>

2022-08-15 23:05 UTC, ViniLopes20 commented
ci:test:sf

2022-08-15 23:05 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/1009/">test-portal-source-format#1009</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1009/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-ac/liferay-portal/pull/29">liferay-ac#29</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1946632608">[master] ci:test:sf - ViniLopes20 &gt; liferay-ac - PR#29 - 2022-08-15[16:00:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/4127/">publish-testray-report#4127</a><br/></div></div>

2022-08-15 23:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/3267/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/3267/jenkins-report.html">here</a>.</b></p>

2022-08-15 23:08 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/62f3e2f73e7ac48f81c19bc25e9396abc1004044">62f3e2f73e7ac48f81c19bc25e9396abc1004044</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/ViniLopes20/liferay-portal/tree/LRAC-11380">LRAC-11380</a><br/>Branch GIT ID: <a href="https://github.com/ViniLopes20/liferay-portal/commit/69328aef2b64ed0df31b1e159c142e7f5f814695">69328aef2b64ed0df31b1e159c142e7f5f814695</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/3267/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/3267/jenkins-report.html">here</a>.</h5></details></html>

2022-08-15 23:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/3267/">test-portal-source-format#3267</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/3267/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-ac/liferay-portal/pull/29">liferay-ac#29</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1946650306">[master] ci:test:sf - ViniLopes20 &gt; liferay-ac - PR#29 - 2022-08-15[16:05:30]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/12234/">publish-testray-report#12234</a><br/></div></div>

2022-08-15 23:17 UTC, ViniLopes20 commented
Hey @christianstokes, the Poshi release is done and I ran both tests locally and they are passing after this ticket. I thought of using the function we asked for Calum _getTimeInMilliseconds_, but in this case, we would need to create a date logic to pass the date 7 days or 1 day ago to the function, with the month and year changes too, it would be very complex.

I think using _MathUtil.difference_ will make it clearer for testing. When I ran SF it changed _MathUtil.difference_ to use "-", I had [asked](https://liferay.slack.com/archives/CD7939WBE/p1656542200082959?thread_ts=1656534095.605969&cid=CD7939WBE) this question to Kenji a few months ago and he said it was expected.

2022-08-17 23:25 UTC, christianstokes approved these changes
Looks great @ViniLopes20. This is a really cool test, and I'm glad everything worked out with the Poshi team. It's always fun to use a totally new function 😀

2022-08-18 00:13 UTC, christianstokes commented
ci:forward

2022-08-18 00:13 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-08-18 00:13 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2022-08-18 00:14 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-38.liferay.com/job/forward-pullrequest/412//consoleFull)

2022-08-18 00:15 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/121857
[Console](https://test-1-38.liferay.com/job/forward-pullrequest/412//consoleFull)

2022-08-18 00:15 UTC, closed without merging